name: 'Publish Auto Management'

on:
  push:
    branches: main
    paths:
      - 'auto_management/**'
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@215271fe54efbdffbece78b02493f7ecd73678f8 # v5.50.0
        with:
          secrets_to_redact: '${{ github.token }}

            ${{ secrets.ACTIONS_GITHUB_TOKEN }}'
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: echo "::set-output name=version::$(cat ./auto_management/DEBIAN/control | grep 'Version' | awk -F\  '{print $2}')"
        id: version
      - run: sudo apt-get install devscripts debhelper
      - run: dpkg-deb --root-owner-group --build ./auto_management/
      - uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release Auto Management v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        id: upload-release-asset 
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: auto_management.deb
          asset_name: auto_management_${{ steps.version.outputs.version }}.deb
          asset_content_type: application/octet-stream
    permissions:
      contents: write
      actions: read
